---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shehabeldeen/backend-app:v1
          ports:
            - name: backend
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8081
      targetPort: backend
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      interval: 5s
      path: /metrics
---
# ? since we are in development, this is acceptable
# ? the reason for doing this is because, when we expose our frontend service on our local machine, and we click on either any of the buttons
# ? our browser will be the one invoking the request not the container as this is a static website and our local machine has no knowledge of the DNS entry
# * please refer to https://www.reddit.com/r/kubernetes/comments/wu5ths/comment/il8a37s/ for more information
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: backend
      nodePort: 30005
