---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: sentinel-dashboard
  template:
    metadata:
      annotations:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/version: "2.1.1"
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: sentinel-dashboard
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: sentinel-dashboard
    spec:
      containers:
        - name: frontend
          image: shehabeldeen/frontend-app:v2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /usr/app/metrics
              name: metrics-storage
          ports:
            - name: frontend
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "128m"
          livenessProbe:
            httpGet:
              path: /health
              port: frontend
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: frontend
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: BACKEND_SVC_BASE_URL
              value: "http://localhost:30005"

            - name: TRIAL_SVC_BASE_URL
              value: "http://localhost:30006"
      volumes:
        - name: metrics-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  labels:
    svc.kubernetes.io/name: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  ports:
    - name: http
      port: 8080
      targetPort: frontend
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  annotations:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      svc.kubernetes.io/name: frontend
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: sentinel-dashboard
  endpoints:
    - port: http
      interval: 5s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  annotations:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: "2.1.1"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  labels:
    svc.kubernetes.io/name: frontend-external
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sentinel-dashboard
  ports:
    - name: http
      port: 8080
      targetPort: frontend
      nodePort: 30004
