---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  # by defaullt this will be added, but this has been added to ensure deterministic deployment
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.42.0
    options:
      collector:
        otlp:
          enabled: true
          grpc:
            host-port: "0.0.0.0:4317"
          http:
            host-port: "0.0.0.0:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-external
  labels:
    app: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger
  ports:
    - name: http-query
      port: 16686
      nodePort: 30002
      protocol: TCP
      targetPort: 16686
    - name: grpc-query
      port: 16685
      protocol: TCP
      targetPort: 16685
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - interval: 5s
      targetPort: 14269
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: jaeger
