apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          # We advise you to build, push and use your own image, instead of using instructor's image.
          image: ghcr.io/jasonsmithio/trial:v1
          ports:
            - name: trial
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial
spec:
  selector:
    app: trial
  ports:
    - name: http
      port: 8082
      targetPort: trial
  type: LoadBalancer
---
# ? since we are in development, this is acceptable
# ? the reason for doing this is because, when we expose our frontend service on our local machine, and we click on either any of the buttons
# ? our browser will be the one invoking the request not the container as this is a static website and our local machine has no knowledge of the DNS entry
# * please refer to https://www.reddit.com/r/kubernetes/comments/wu5ths/comment/il8a37s/ for more information
apiVersion: v1
kind: Service
metadata:
  name: trial-external
spec:
  type: NodePort
  selector:
    app: trial
  ports:
    - port: 8080
      targetPort: trial
      nodePort: 30006