---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configs
data:
  DB_HOST: "mongodb.default"
  DB_PORT: "27017"
  DB_NAME: "galaxyDb"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  DB_ROOT_USER: "cm9vdA=="
  DB_ROOT_PASSWORD: "aWFtcm9vdG9obGFsYQ=="
  DB_USER: "aGFtYWRh"
  DB_PASSWORD: "d293aW1zb3NlY3VyZQ=="
  DB_AUTH_SRC: "YWRtaW4="
