{
 "title": "Sentinel Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Frontend Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(namespace, service) (\n\n   (last_over_time(kube_pod_completion_time{pod=~\"frontend.*\"}[1d])\n   - last_over_time(kube_pod_created{pod=~\"frontend.*\"}[1d])) \n\n  or \n\n    (time() - kube_pod_created{pod=~\"frontend.*\"})\n\n) ",
     "legendFormat": "Uptime"
    },
    {
     "expr": "group by(container)(up{job=~\"frontend\"})",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(namespace, service) (\n\n   (last_over_time(kube_pod_completion_time{pod=~\"backend.*\"}[1d])\n   - last_over_time(kube_pod_created{pod=~\"backend.*\"}[1d])) \n\n  or \n\n    (time() - kube_pod_created{pod=~\"backend.*\"})\n\n) ",
     "legendFormat": "Uptime"
    },
    {
     "expr": "group by(container)(up{job=~\"backend\"})",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image=~\".*/frontend-app.*|.*/backend-app.*\"}[1m])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{image=~\".*/frontend-app.*|.*/backend-app.*\"}[1m])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Frontend Latency - 99 Percentile",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "service": "frontend-service" }
   ]
  },
  {
   "title": "Backend Latency - 99 Percentile",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "service": "backend-service" }
   ]
  },
  {
   "title": "5XX Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container)(rate(frontend_service_http_request_duration_seconds_count{status=~\"5..\"}[30s]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum by(container)(rate(backend_service_http_request_duration_seconds_count{status=~\"5..\"}[30s]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "4XX Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container)(rate(frontend_service_http_request_duration_seconds_count{status=~\"4..\"}[30s]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum by(container)(rate(backend_service_http_request_duration_seconds_count{status=~\"4..\"}[30s]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "2XX Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container)(rate(frontend_service_http_request_duration_seconds_count{status=~\"2..\"}[30s]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum by(container)(rate(backend_service_http_request_duration_seconds_count{status=~\"2..\"}[30s]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Frontend Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, status)(increase(frontend_service_http_request_total[1m]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Backend Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(method, status)(increase(backend_service_http_request_total[1m]))",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Frontend Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path)(rate(frontend_service_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(frontend_service_http_request_duration_seconds_count{status=\"200\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Backend Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path)(rate(backend_service_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(backend_service_http_request_duration_seconds_count{status=\"200\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}